### ISSUE TITLE
Improve error message if no broker is running

### ISSUE THREAD

**Issue by berndruecker** [zeebe-io/zbc-go#133]
If no broker is running you get the following exception when using zbctl - it is hard to guess the real problem:

```
C:\Camunda\zeebe-broker-0.7.0\zbctl>zbctl create topic --name default-topic --partitions 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x5fb240]

goroutine 19 [running]:
github.com/zeebe-io/zbc-go/zbc.(*dispatcher).addTransaction(...)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/dispatcher.go:17
github.com/zeebe-io/zbc-go/zbc.(*transportManager).transportWorker.func1(0xbea411664f0e7a18, 0x3df1bae8, 0x7dc0a0)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/transport_manager.go:48 +0x30
github.com/zeebe-io/zbc-go/zbc.MessageRetry(0xc0420edfb0, 0xc0420edfa0, 0xd, 0x0)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/retry.go:89 +0xc4
github.com/zeebe-io/zbc-go/zbc.(*transportManager).transportWorker(0xc042040b90)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/transport_manager.go:47 +0x5b
created by github.com/zeebe-io/zbc-go/zbc.newTransportManager
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/transport_manager.go:65 +0xe2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x5f50e7]

goroutine 1 [running]:
github.com/zeebe-io/zbc-go/zbc.(*responseHandler).unmarshalTopology(0xc0420665a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/response.go:21 +0xb7
github.com/zeebe-io/zbc-go/zbc.(*topologyManager).initTopology(0xc04207ac60, 0x68e738, 0xc04207ac60, 0x0)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/topology_manager.go:77 +0x153
github.com/zeebe-io/zbc-go/zbc.newTopologyManager(0xc0420d20a0, 0xd, 0xc042066728)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/topology_manager.go:181 +0x161
github.com/zeebe-io/zbc-go/zbc.newRequestManager(0xc0420d20a0, 0xd, 0xc042040b70)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/request_manager.go:238 +0x74
github.com/zeebe-io/zbc-go/zbc.NewClient(0xc0420d20a0, 0xd, 0xd, 0xc04209a580, 0x1c60a8)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/zbc/client.go:119 +0x40
main.main.func2(0xc04209a580, 0x100, 0xc04209a580)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/cmd/main.go:141 +0x54
github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli.HandleAction(0x632e60, 0xc042040680, 0xc04209a580, 0xc042086300, 0x0)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli/app.go:491 +0xd9
github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli.Command.Run(0x67faed, 0x5, 0x0, 0x0, 0xc042040700, 0x1, 0x1, 0x682720, 0x12, 0x0, ...)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli/command.go:212 +0xa9c
github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc042050820, 0xc04209a160, 0x0, 0x0)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli/app.go:380 +0xa82
github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli.Command.startApp(0x67fcbc, 0x6, 0x0, 0x0, 0xc0420406f0, 0x1, 0x1, 0x68243e, 0x11, 0x0, ...)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli/command.go:299 +0x927
github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli.Command.Run(0x67fcbc, 0x6, 0x0, 0x0, 0xc0420406f0, 0x1, 0x1, 0x68243e, 0x11, 0x0, ...)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli/command.go:98 +0x13d4
github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli.(*App).Run(0xc042050680, 0xc042072000, 0x7, 0x8, 0x0, 0x0)
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/vendor/github.com/urfave/cli/app.go:256 +0x6ff
main.main()
        /home/travis/gopath/src/github.com/zeebe-io/zbc-go/cmd/main.go:403 +0x197d
```

**Comment by menski** [comment]
This should be fixed with the next zbc release. I will keep the ticket open until the release is out. Thanks for the feedback
